# Generated by Django 5.1.6 on 2026-03-17 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_city_area', models.CharField(blank=True, max_length=100)),
                ('preferred_property_type', models.CharField(blank=True, choices=[('3BHK', '3 BHK'), ('2BHK', '2 BHK'), ('1BHK', '1 BHK'), ('1RK', '1 RK'), ('SR', 'Single Room')], max_length=10)),
                ('max_budget', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
